# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0009_video_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
